# Generated by Django 4.0.4 on 2022-04-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='head',
            name='text_1',
            field=models.CharField(blank=True, max_length=120, verbose_name='Текст на первом слайде'),
        ),
        migrations.AddField(
            model_name='head',
            name='text_2',
            field=models.CharField(blank=True, max_length=120, verbose_name='Текст на втором слайде'),
        ),
    ]
