# Generated by Django 4.0.4 on 2022-04-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0002_head_text_1_head_text_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адрес')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Email')),
            ],
            options={
                'verbose_name': '       Контактные данные',
                'verbose_name_plural': '       Контактные данные',
            },
        ),
    ]
