# Generated by Django 4.0.4 on 2022-04-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0005_info_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(blank=True, default='', upload_to='', verbose_name='Иконка')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=150, verbose_name='Текст')),
            ],
            options={
                'verbose_name': '       Задача обучения',
                'verbose_name_plural': '       Задачи обучения',
            },
        ),
    ]
