# Generated by Django 4.0.4 on 2022-04-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0007_welcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bg',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Цвет блока'),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='text',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Текст'),
        ),
    ]
