# Generated by Django 4.0.4 on 2022-04-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0008_task_bg_alter_welcome_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='bg',
        ),
        migrations.AddField(
            model_name='info',
            name='bg',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Цвет блока'),
        ),
    ]
