# Generated by Django 4.0.4 on 2022-04-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0010_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=50, verbose_name='Название раздела')),
                ('intro', models.CharField(blank=True, max_length=1000, verbose_name='Описание раздела')),
                ('image', models.FileField(blank=True, default='', upload_to='', verbose_name='Фото')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя, фамилия')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='Должность')),
                ('description', models.CharField(blank=True, max_length=120, verbose_name='О преподавателе')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
