# Generated by Django 4.0.4 on 2022-04-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0011_stuff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=50, verbose_name='Название раздела')),
                ('intro', models.CharField(blank=True, max_length=1000, verbose_name='Описание раздела')),
                ('image', models.FileField(blank=True, default='', upload_to='', verbose_name='Фото')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя, фамилия')),
                ('testimonial', models.CharField(blank=True, max_length=1500, verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AlterField(
            model_name='stuff',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='О преподавателе'),
        ),
    ]
