# Generated by Django 4.0.4 on 2022-04-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0013_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=2000, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Интересная информация',
                'verbose_name_plural': 'Интересная информация',
            },
        ),
    ]
