# Generated by Django 4.0.4 on 2022-04-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0014_interestinginfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=50, verbose_name='Название раздела')),
                ('intro', models.CharField(blank=True, max_length=1000, verbose_name='Описание раздела')),
                ('image', models.FileField(blank=True, default='', upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
    ]
