# Generated by Django 4.0.4 on 2022-04-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0015_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='section',
        ),
    ]
