# Generated by Django 4.0.4 on 2022-04-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0016_remove_gallery_intro_remove_gallery_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=1000, verbose_name='Текст')),
            ],
            options={
                'verbose_name': '     Пробный урок (форма записи)',
                'verbose_name_plural': '     Пробный урок (форма записи)',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '         Контактные данные', 'verbose_name_plural': '         Контактные данные'},
        ),
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': '  Сообщение, заказ', 'verbose_name_plural': '  Сообщения, заказы'},
        ),
        migrations.AlterModelOptions(
            name='head',
            options={'verbose_name': '          Верхняя часть с фото', 'verbose_name_plural': '          Верхняя часть с фото'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': '        Инфо', 'verbose_name_plural': '        Инфо'},
        ),
        migrations.AlterModelOptions(
            name='interestinginfo',
            options={'verbose_name': ' Интересная информация', 'verbose_name_plural': ' Интересная информация'},
        ),
        migrations.AlterModelOptions(
            name='stuff',
            options={'verbose_name': '    Преподаватель', 'verbose_name_plural': '    Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': '   Отзыв', 'verbose_name_plural': '   Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='trial',
            options={'verbose_name': '     Пробный урок', 'verbose_name_plural': '     Пробный урок'},
        ),
        migrations.AlterModelOptions(
            name='welcome',
            options={'verbose_name': '      Добро пожаловать', 'verbose_name_plural': '      Добро пожаловать'},
        ),
    ]
