# Generated by Django 4.0.4 on 2022-04-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0017_trialform_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=50, verbose_name='Название раздела')),
                ('intro', models.CharField(blank=True, max_length=1000, verbose_name='Описание раздела')),
                ('subtitle', models.CharField(blank=True, max_length=30, verbose_name='Название цены')),
                ('price', models.CharField(blank=True, max_length=10, verbose_name='Цена')),
                ('image', models.FileField(blank=True, default='', upload_to='', verbose_name='Фото')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name': '     Цена',
                'verbose_name_plural': '     Цены',
            },
        ),
    ]
