# Generated by Django 4.0.4 on 2022-04-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0018_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': '     Цена (ровно 4 цены)', 'verbose_name_plural': '     Цены (ровно 4 цены)'},
        ),
    ]
